baseURL: "https://kha8128.github.io/" 
title: Hyuna Kwon
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

#social:
#    twitter: pmichaillat

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications 
          url: /publications/
#          weight: 1
#        - name: Courses
#          url: /courses/
#          weight: 2
#        - name: Design
#          url: /design/
#          weight: 3
#        - name: Tags
#          url: /tags/
#          weight: 5    
        - name: CV
          url: /cv/
          weight: 3
#        - name: Newsletter
#          url: https://pmichaillat.substack.com
#          weight: 4

params:
    description: "Greetings! I am Hyuna Kwon, a postdoctoral researcher at Lawrence Livermore National Lab. My research focuses on computational chemistry, machine learning, and materials science.

I am passionate about the intersection of AI and materials discovery, particularly in energy applications and sustainability. Please check out my CV and publications for more details about my work."
    author: Hyuna Kwon
    #googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Hyuna Kwon 
          subtitle: "Postdoctoral researcher at Lawrence Livermore National Lab. My research focuses on computational chemistry and AI-driven materials science."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Hyuna Kwon
          buttons:
#            - name: Papers
#              url: /papers/
            - name: About 
              url: /about/
            - name: Publications 
              url: /publications/
            #- name: Newsletter
            #  url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: kwon11@llnl.gov
#        - name: Location
#          url: /location/
#        - name: Office Hours
#          url: /officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=Oq-hGnwAAAAJ&hl=en
        #- name: YouTube
        #  url: https://www.youtube.com/@pmichaillat
        #- name: GitHub
        #  url: https://github.com/pmichaillat?tab=repositories

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Hyuna Kwon"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120â€“155
# * summary: 265
